server:
  port: 8081

spring:
  application:
    name: zero-ddd-gateway
#  graphql:
#    graphiql:
#      enabled: true
  cache:
    multi:
      l1-cache:
        spec: "initialCapacity=100,maximumSize=500,expireAfterAccess=5m,recordStats"
      cache-names: user
      server-id: server-2
      cache-prefix: multi
      l2-cache:
        default-expiration: 60s
        default-null-values-expiration: 120s


    type: caffeine
    caffeine:
      spec: "initialCapacity=100,maximumSize=500,expireAfterAccess=5m,recordStats"
    cache-names: user,role


  redis:
    redisson:
      file: classpath:redisson.yml