
spring:
  messages:
    basename: messages
  application:
    name: zero-ddd-gateway
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
      config:
        enabled: false
    gateway:
      routes:
        - id: zero-ddd-tenant
          uri: lb://zero-ddd-tenant
          order: 0
          predicates:
            - Path=/tenant/**
        - id: zero-ddd-main
          uri: lb://zero-ddd-main
          order: 0
          predicates:
            - Path=/main/**
        - id: zero-ddd-auth
          uri: lb://zero-ddd-auth
          order: 0
          predicates:
            - Path=/auth/**

  redis:
    redisson:
      file: classpath:redisson.yml

security:
  context:
    enabled-access: true
  filter:
    ignore-url:
      - /auth/login/username
      - /auth/logout
  jwt:
    enabled: true


