
spring:
  messages:
    basename: messages
  application:
    name: zero-ddd-gateway
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
      config:
        enabled: false
    gateway:
      routes:
        - id: zero-ddd-tenant
          uri: lb://zero-ddd-tenant
          order: 0
          predicates:
            - Path=/tenant/**

  redis:
    redisson:
      file: classpath:redisson.yml
security:
  filter:
    ignore-url:
      - /tenant/login/username


