server:
  port: 8081

spring:
  application:
    name: zero-ddd-gateway
  graphql:
    graphiql:
      enabled: true



  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: h2
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true