spring:
  application:
    name: zero-example
  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-returns: true # 队列确认
    publisher-confirm-type: correlated # 交换机确认
  messages:
    basename: messages
  modulith:
    detection-strategy: explicitly-annotated
    events:
      republish-outstanding-events-on-restart: true
      externalization:
        enabled: true
  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/zero-example
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
#  h2:
#    console:
#      enabled: true
  liquibase:
    enabled: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    database: PostgreSQL
    defer-datasource-initialization: false
    open-in-view: false
multi-tenancy:
  datasource:
    url: jdbc:postgresql://localhost:5432/zero-tenant
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    database: PostgreSQL
  redis:
    redisson:
      file: classpath:redisson.yml