server:
  port: 8082

spring:
  application:
    name: zero-ddd-main
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
      config:
        enabled: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: h2
    defer-datasource-initialization: false
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    # 如下配置是被spring.datasource赋值的，所以可以不配置
    #    url: jdbc:mysql://localhost:3306/test_db_liquibase?useSSL=false&autoReconnect=true&characterEncoding=utf8
    #    user: root
    #    password: bfXa4Pt2lUUScy8jakXf
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  graphql:
    graphiql:
      enabled: true
      path: /main/graphiql
    path: /main/graphql

  redis:
    redisson:
      file: classpath:redisson.yml

multi-tenancy:
  database: h2
  database-pattern:
    url-prefix: "jdbc:h2:mem:"
  schema-pattern:
    schema: "PUBLIC"



logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy=DEBUG:
