server:
  port: 8081

spring:
  modulith:
    detection-strategy: explicitly-annotated
  messages:
    basename: messages
  # swagger-ui custom path
#  swagger-ui:
#    path: swagger-ui.html

  application:
    name: zero-ddd-tenant
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
      config:
        enabled: false
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        multiTenancy: true
        tenant_identifier_resolver: com.zjj.tenant.column.component.TenantIdentifierResolver
        format_sql: true
    database: h2
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

  graphql:
    graphiql:
      enabled: true
      path: /tenant/graphiql
    path: /tenant/graphql
  redis:
    redisson:
      file: classpath:redisson.yml

management:
  endpoints:
    web:
      exposure:
        include: startup


logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy=DEBUG:
security:
  username-login:
    enabled: true
    login-path: /tenant/login/username
  logout-path: /tenant/logout