security:
  username-login:
    enabled: true

spring:
  application:
    name: graphApplication
#  graphql:
#    graphiql:
#      enabled: true
  cache:
    multi:
      l1-cache:
        spec: "initialCapacity=100,maximumSize=500,expireAfterAccess=5m,recordStats"

    type: caffeine
    caffeine:
      spec: "initialCapacity=100,maximumSize=500,expireAfterAccess=5m,recordStats"
    cache-names: user,role


  redis:
    redisson:
      file: classpath:redisson.yml