server:
  port: 8083

spring:
  application:
    name: zero-ddd-auth
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
      config:
        enabled: false

  redis:
    redisson:
      file: classpath:redisson.yml

logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy=DEBUG:
security:
  context:
    enabled-access: false
    enabled-login-handler: true
  username-login:
    enabled: true
    login-path: /auth/login/username
