security:
  username-login:
    enabled: true

spring:
  application:
    name: graphApplication
#  graphql:
#    graphiql:
#      enabled: true
  cache:
    type: caffeine
    caffeine:
      spec: "initialCapacity=100,maximumSize=500,expireAfterAccess=5m,recordStats"